name: do_an_phan_loai_rac
description: "Dự án phân loại rác thải bằng AI - K23 HUTECH"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.12.0+1
  tflite_flutter: ^0.12.1
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Khai báo file Model và Labels để AI hoạt động
  assets:
    - assets/labels.txt
    - assets/model_rac_thai.tflite
    